version: "3.8"

services:
  docker-mysql:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yollo
      MYSQL_DATABASE: yollo_app
    networks: 
      springboot-yollo-app-net:
  
  yollo-app:
    container_name: yollo-app-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - docker-mysql
    networks:
       springboot-yollo-app-net:
    restart: on-failure
    
networks:
  springboot-yollo-app-net:
      