version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yollo
      MYSQL_DATABASE: yollo_app
          
  yollo-app:
    container_name: yollo-app-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    restart: on-failure
    
networks:
  default:
    name: springboot-yollo-app-net
      